### ISSUE TITLE
Several code and cryptographic quality issues

### ISSUE THREAD

**Issue by SN4T14** [MauriceButler/cryptr#1]
1. You should never, ever have a default key, a default key is as good as no key, if no secret is given, an error should be thrown.

2. `!secret` is not the correct way to check whether the `secret` variable is undefined or not, neither is `algorithm || 'aes256'`. If you want to check whether the argument was passed or not, you should do `secret == null`.

3. You should make sure `secret` is either a string or a buffer.

4. The `encrypt` and `decrypt` functions will throw a `TypeError` if passed `null` or `undefined` as any attempt to access their properties results in one. This is potentially correct behaviour, but should be documented, and the error should potentially be caught and a more descriptive error thrown.

5. The default cipher is `aes256`, which OpenSSL aliases to `AES-256-CBC`, CBC mode is a [bad idea](https://crypto.stackexchange.com/questions/25089/plaintext-block-chaining-bad-idea-why), a more sane default cipher would be `AES-256-CTR`, as it should be supported everywhere, and does not suffer the same issues as CBC mode. Additionally, NaCl, often considered one of the most secure cryptographic libraries available, [uses CTR mode](https://nacl.cr.yp.to/stream.html) for their unauthenticated secret-key encryption, authenticated encryption would be a better choice, but GCM is unsupported in Node as it requires more arguments than other modes.

**Comment by MauriceButler** [comment]
Hi @SN4T14 

Thanks for your input.

This I haven't looked at this package for a while and could probably do with some updating.

I agree on point 1, it is something I have been meaning to remove but it hasn't been urgent or of value to me as yet as no one would actually use that. Right.... :S

Points 2, 3 and 4, sounds like we have different coding styles :) I don't explicitly care if the variables were passed or if bad data was passed. It is there purely for checking if a default should be applied, and as you point out they shouldn't be. 

While I understand your desire for cleaner messages in my experience a runtime exception with a full stack is much more useful to a developer and thus I code that way.

Point 5, thanks for the information on the OpenSSL alias. I will either make the switch or remove the default all together, I am not sure which yet.

I wont get to this for a little while so if you feel strongly and would like to submit a pull request I am more than happy to merge it in. Otherwise I will update this issue when I update the package.

Thanks.

**Comment by SN4T14** [comment]
>Points 2, 3 and 4, sounds like we have different coding styles :) I don't explicitly care if the variables were passed or if bad data was passed. It is there purely for checking if a default should be applied, and as you point out they shouldn't be.

These are most definitely not different coding styles, as neither `!a` not `a || b` are just checking "is this value null or undefined", it's checking whether `a` is [falsy](https://developer.mozilla.org/en-US/docs/Glossary/falsy), which isn't always the most logically defined thing in JavaScript.

Point 3 has nothing to do with coding style at all, `crypto.createCipher()` only accepts string or buffer arguments, and odds are if one of those isn't passed, the user did something wrong.

Point 4 still stands, if throwing a TypeError is intended functionality, it should be documented.

>Point 5, thanks for the information on the OpenSSL alias. I will either make the switch or remove the default all together, I am not sure which yet.

You should always have a sane default algorithm, otherwise people are just going to start passing `aes256` as the algorithm because that was the default.

Anyway, I'll probably fix these issues and submit a pull request in a few hours.

**Comment by KoryNunn** [comment]
I'd change the secret check to

```
if(!secret || typeof secret !== 'string'){
    throw new Error('secret must be a non 0-length string');
}
```

since we only care about strings greater than 0 length.

**Comment by KoryNunn** [comment]
https://github.com/MauriceButler/cryptr/pull/2

**Comment by joepie91** [comment]
> While I understand your desire for cleaner messages in my experience a runtime exception with a full stack is much more useful to a developer and thus I code that way.

For expected errors (eg. failed input validation), a 'full stack' is unnecessary and irrelevant - the code shouldn't even *get* to the point where such an error would be generated, but fail early instead. So it shouldn't even really be catching the error (as @SN4T14 suggested), but rather explicitly check for them being defined and throw an error when they're not.

Other than that, @SN4T14 is correct re: point 2 - checking for something being defined and checking for something being truthy are *absolutely not* the same thing, and these are *not* interchangeable. This is not a matter of style. The only correct approach is `== null` to check whether something is undefined, and `!= null` to check whether something is defined.

You really should not rely on side-effects of imprecise variable checks - this is the only correct syntax there:

```javascript
if(secret == null || typeof secret !== 'string' || secret.length === 0){
    throw new Error('secret must be a non 0-length string');
}
```

Similarly, for the algorithm check:

```javascript
if (algorithm == null) {
    algorithm = 'aes256';
}
```

... except, as @SN4T14 suggested, with a better default.

**Comment by KoryNunn** [comment]
@MauriceButler and myself are well aware of how JavaScript works.

Checking that algorithm is not null or undefined will not help users that pass other non-string values.

Given that the code in the PR is functional correct, this is now a discussion on style.

If you do not think the code is functionally correct, you can show this via a unit test.

**Comment by joepie91** [comment]
@KoryNunn Existence checking and type checking are two separate checks (and the algorithm checking code remains wrong in your PR). I don't see how a unit test would be relevant here - I've already pointed out the problem quite clearly.

If you consider it appropriate to demand practical proof of a theoretically provable problem, you *really should not be writing crypto code*. Any crypto-related code that is any less than 100% perfect is to be considered broken and needs-fixing, because of how hard it is to get crypto right.

Seriously, just don't write/publish crypto code if you're not willing to fulfill the associated effort required. Just point people at an established implementation, preferably libsodium/NaCL.
