### ISSUE TITLE
Some additional error handling needed maybe?

### ISSUE THREAD

**Issue by karlpokus** [MauriceButler/cryptr#4]
Hi @MauriceButler Thanks for sharing your code. I've had some wierd results and would like your input.
1. When _passing the wrong key to decrypt_ `aes-X-ctr` returns wierd data (not even characters I recognize) compared to `aesX` that throws an error.
2. Why _decrypting an unencrypted string_ `aes-256-ctr` returns an empty string while `aes-192-ctr` throws an error.

I'm trying to figure out how to handle this in production. I don't think these cases are included in your tests but I could be wrong.

**Comment by MauriceButler** [comment]
Hi mate,

I think this is going to be more the functionality of the underlying node crypto module rather than this module itself as this is just a simple wrapper around the api.

Can you reproduce the same issues using the crypto library directly? 
[Crypto docs](https://nodejs.org/api/crypto.html) 
[Current implementation](https://github.com/MauriceButler/cryptr/blob/master/index.js#L22)

And if so with which version(s) of node?

I assume that if this is in fact an issue / unexpected behaviour of the cipher / deciphers it should probably be raised on the node repo.

**Comment by karlpokus** [comment]
@MauriceButler Maybe you're right. Got the same issues with crypto core using node 4.2.1 Wierd.
